CREATE SINK KAFKA_SINK(EVENT_NAME VARSIZED NOT NULL, TIMESTAMP UINT64, EVENT_ID UINT64) TYPE Kafka SET ('JSON' AS `SINK`.OUTPUT_FORMAT, 'localhost:9092' AS  `SINK`.BROKERS, 'process-intelligence' AS `SINK`.TOPIC);

CREATE LOGICAL SOURCE FILE_SOURCE(FIELD1 UINT64, FIELD2 UINT64);
CREATE PHYSICAL SOURCE FOR FILE_SOURCE TYPE File SET('CSV' AS parser.`TYPE`, '\n' AS parser_config.tuple_delimiter, ',' AS parser_config.field_delimiter, './_local/1million.csv' AS `SOURCE`.file_path);

SELECT VARSIZED("hello_world") AS EVENT_NAME, field1 AS TIMESTAMP, field1 AS EVENT_ID FROM (SELECT field1, field2, field1 + UINT64(1) AS NEW_FIELD FROM FILE_SOURCE) INTO KAFKA_SINK;


SHOW QUERIES;
