data_rate: 1
period: 1000
chunk_size: 1000

pattern:
  - type: uniform
  #- fraction: 0.5
  #- distribution: 0.5

data_source:
  type: "image_folder"
  file: "/app/data/transistor"
  encoding: "base64"

duration: 60000
host: "0.0.0.0"
ports:
  - 8080
  - 8081
  - 8082

mqtt:
  enabled: false
  host: "mosquitto"
  port: 1883
  topic: "bid"

zipf:
  period_ms: 1000
  s: 1.4
  stochastic: true
