data_rate: 1
period: 1000
chunk_size: 1000

pattern:
  - type: uniform

data_source:
  type: "image_folder"
  file: "demo/data/engine_wiring"
  encoding: "base64"

duration: 60000000
host: "0.0.0.0"
ports:
  - 8080
  - 8081
  - 8082

mqtt:
  enabled: false
  host: 172.26.0.1
  port: 1882
  topic: "bid"

zipf:
  period_ms: 1000
  s: 1.4
  stochastic: true
